name: 'soma'
author: 'J3di'
description: 'Somar dois números.'
inputs:
  a:
    required: true
  b:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v5 # Upgrade from v4 to v6
      with:
        python-version: '3.12'

    - name: run soma
      shell: bash
      run: python soma.py -a=${{ inputs.a }} -b=${{ inputs.b }}
